version: "3"

volumes:
  conf-volume: {}
  vhost-volume: {}
  html-volume: {}
  certs-volume: {}

services:
  nginx:
    restart: always
    image: nginx
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf-volume:/etc/nginx/conf.d
      - vhost-volume:/etc/nginx/vhost.d
      - html-volume:/usr/share/nginx/html
      - certs-volume:/etc/nginx/certs:ro
    networks:
      - proxy-tier
    deploy:
      placement:
        constraints: [node.role == manager]

  nginx-gen:
    restart: always
    image: docker-gen-swarm
    build: ./compose/docker-gen-docker-cloud/
    depends_on:
      - nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      #- /var/run/docker.sock:/var/run/docker.sock:ro
      - ./volumes/proxy/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - conf-volume:/etc/nginx/conf.d
      - vhost-volume:/etc/nginx/vhost.d
      - html-volume:/usr/share/nginx/html
      - certs-volume:/etc/nginx/certs:ro
    networks:
      - proxy-tier
    deploy:
      placement:
        constraints: [node.role == manager]
    entrypoint: /usr/local/bin/docker-gen -notify-output -notify "/restart_service.sh" -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

  letsencrypt-nginx-proxy-companion:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    depends_on:
      - nginx
      - nginx-gen
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs-volume:/etc/nginx/certs:rw
      - conf-volume:/etc/nginx/conf.d
      - vhost-volume:/etc/nginx/vhost.d
      - html-volume:/usr/share/nginx/html
    deploy:
      placement:
        constraints: [node.role == manager]

  # sample-api:
  #   restart: always
  #   image: sample-api
  #   build: ./samples/api
  #   container_name: sample-api
  #   environment:
  #     - VIRTUAL_HOST=sampleapi.example.com
  #     - VIRTUAL_NETWORK=nginx-proxy
  #     - VIRTUAL_PORT=3000
  #     - LETSENCRYPT_HOST=sampleapi.example.com
  #     - LETSENCRYPT_EMAIL=email@example.com

  # sample-website:
  #   restart: always
  #   image: sample-website
  #   build: ./samples/website
  #   container_name: sample-website
  #   volumes:
  #     - "./volumes/nginx-sample-website/conf.d/:/etc/nginx/conf.d"
  #     - "./volumes/config/sample-website/config.js:/usr/share/nginx/html/config.js"
  #   environment:
  #     - VIRTUAL_HOST=samplewebsite.example.com
  #     - VIRTUAL_NETWORK=nginx-proxy
  #     - VIRTUAL_PORT=80
  #     - LETSENCRYPT_HOST=sample.example.com
  #     - LETSENCRYPT_EMAIL=email@example.com

networks:
  proxy-tier:
    external:
      name: "nginx-proxy"
